version: '3.8'

services:
  app:
    build: .
    container_name: journalistic_app
    ports:
      - "8000:80"
    depends_on:
      - db
      - neo4j

  db:
    image: postgres:latest
    container_name: journalistic_db
    environment:
      POSTGRES_DB: journalistic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/test"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  neo4j_data:
